CREATE OR REPLACE FUNCTION X0DESPFA.FNC_DET_CCAF(
    p_anio            VARCHAR2,
    p_mes             VARCHAR2,
    p_con_rut         NUMBER,
    p_con_correl      NUMBER,
    p_rpr_proceso     NUMBER,
    p_nro_comprobante NUMBER,
    p_tipo_corte      NUMBER,
    p_cod_corte       VARCHAR2,
    p_anio_suc_du     VARCHAR2,
    p_mes_suc_du      VARCHAR2,
    p_anio_new_rem    VARCHAR2,
    p_mes_new_rem     VARCHAR2
) RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT
    TO_CHAR(E.REC_PERIODO, 'MM') AS PER_MES,
    TO_CHAR(E.REC_PERIODO, 'YYYY') AS PER_ANIO,
    E.RPR_PROCESO,
    EXTRACT(MONTH FROM E.EMP_FECINI_RPR) AS GRAT_MES_INI,
    EXTRACT(YEAR FROM E.EMP_FECINI_RPR) AS GRAT_ANIO_INI,
    EXTRACT(MONTH FROM E.EMP_FECTER_RPR) AS GRAT_MES_TER,
    EXTRACT(YEAR FROM E.EMP_FECTER_RPR) AS GRAT_ANIO_TER,
    C.ENT_NOMBRE,
    CASE 
        WHEN TO_CHAR(p_tipo_corte) = 3 THEN 'Suc_cod: ' || TO_CHAR(P.SUC_CODIGO)
        WHEN TO_CHAR(p_tipo_corte) = 4 THEN 'Usu_cod : ' || TO_CHAR(P.USU_CODIGO)
        WHEN TO_CHAR(p_tipo_corte) = 1 AND ((TO_CHAR(p_anio) = TO_CHAR(p_anio_suc_du) AND TO_CHAR(p_mes) >= TO_CHAR(p_mes_suc_du)) OR TO_CHAR(p_anio) > TO_CHAR(p_anio_suc_du)) THEN 'Suc_codigo :' || TO_CHAR(T.SUC_CODIGO)
        WHEN TO_CHAR(p_tipo_corte) = 2 AND ((TO_CHAR(p_anio) = TO_CHAR(p_anio_suc_du) AND TO_CHAR(p_mes) >= TO_CHAR(p_mes_suc_du)) OR TO_CHAR(p_anio) > TO_CHAR(p_anio_suc_du)) THEN 'Usu_codigo :' || TO_CHAR(T.USU_CODIGO)
        ELSE ''
    END AS SUC_COD,
    CASE
        WHEN TO_CHAR(p_tipo_corte) = 4 THEN 'Usu_cod : ' || TO_CHAR(P.USU_CODIGO)
        ELSE ''
    END AS USU_COD,
    E.EMP_RUT,
    E.EMP_DIGITO,
    E.EMP_RAZSOC,
    P.PLA_NRO_SERIE,
   -- P.PLA_NRO_HOJ,
    T.TRA_RUT,
    T.TRA_DIGITO,
    T.TRA_APETRA,
    T.TRA_NOMTRA,
    T.TRA_REG_SALUD,
    NVL(CCAF.CCAF_SALUD, 0) AS TRACCAF_SALUD,
    CASE WHEN CCAF.CCAF_SALUD IS NOT NULL THEN 1 ELSE 0 END AS IMP06SALUD,
    CASE
        WHEN (TO_CHAR(p_anio) = TO_CHAR(p_anio_new_rem) AND TO_CHAR(p_mes) >= TO_CHAR(p_mes_new_rem)) OR TO_CHAR(p_anio) > TO_CHAR(p_anio_new_rem)
        THEN NVL(T.TRA_REM_CCAF, 0)
        WHEN T.RPR_PROCESO = 1 AND T.TRA_REG_PREVIS = 0 THEN T.TRA_REMIMP_INPCCAF
        WHEN T.RPR_PROCESO = 1 AND T.TRA_REG_PREVIS NOT IN (0, 90) AND T.TRA_REG_PREVIS IS NOT NULL AND T.REC_PERIODO >= TO_DATE('31-01-2010', 'DD-MM-YYYY') THEN T.TRA_REM_IMP_AFP
        ELSE T.TRA_REM_IMPONIBLE
    END AS TRA_REM_IMPO,
    T.TRA_NRO_DIAS_TRAB,
    T.TRA_DES_NACIONALIDAD,
    T.TRA_NRO_CAR_SIM,
    T.TRA_NRO_CAR_INV,
    T.TRA_NRO_CAR_MAT,
    T.TRA_MTO_ASIG_FAM,
    T.TRA_TRAMO_ASIG_FAM,
    NVL(TO_CHAR(M.RTM_TIPO), '') AS MOV_TIPO,
    M.MOV_FECINI,
    M.MOV_FECTER,
    EXTRACT(DAY FROM PG.PAG_FECTIMBRE) AS DIA_PAGO,
    EXTRACT(MONTH FROM PG.PAG_FECTIMBRE) AS MES_PAGO,
    EXTRACT(YEAR FROM PG.PAG_FECTIMBRE) AS ANIO_PAGO,
    TO_CHAR(T.TRA_RUT) || T.USU_CODIGO || T.SUC_CODIGO AS x
FROM REC_EMPRESA E
JOIN REC_TRABAJADOR T ON E.REC_PERIODO = T.REC_PERIODO AND E.CON_RUT = T.CON_RUT AND E.CON_CORREL = T.CON_CORREL
                    AND E.RPR_PROCESO = T.RPR_PROCESO AND E.NRO_COMPROBANTE = T.NRO_COMPROBANTE
LEFT JOIN REC_TRACCAF CCAF ON ((TO_CHAR(p_rpr_proceso) <> 2 OR TO_CHAR(p_anio) > 2007 OR (TO_CHAR(p_anio) = '2007' AND TO_CHAR(p_mes) = '12'))
                            AND T.REC_PERIODO = CCAF.REC_PERIODO AND T.CON_RUT = CCAF.CON_RUT AND T.CON_CORREL = CCAF.CON_CORREL
                            AND T.TRA_RUT = CCAF.TRA_RUT AND T.SUC_CODIGO = CCAF.SUC_CODIGO AND T.RPR_PROCESO = CCAF.RPR_PROCESO AND T.NRO_COMPROBANTE = CCAF.NRO_COMPROBANTE AND T.USU_CODIGO = CCAF.USU_CODIGO)
JOIN REC_PAGO PG ON E.REC_PERIODO = PG.REC_PERIODO AND E.CON_RUT = PG.CON_RUT AND E.CON_CORREL = PG.CON_CORREL
              AND E.RPR_PROCESO = PG.RPR_PROCESO AND E.NRO_COMPROBANTE = PG.NRO_COMPROBANTE
JOIN REC_PLANILLA P ON T.REC_PERIODO = P.REC_PERIODO AND T.NRO_COMPROBANTE = P.NRO_COMPROBANTE
                AND ((TO_CHAR(p_tipo_corte) = 3 AND P.SUC_CODIGO = T.SUC_CODIGO) OR (TO_CHAR(p_tipo_corte) = 4 AND P.USU_CODIGO = T.USU_CODIGO) OR (TO_CHAR(p_tipo_corte) NOT IN (3, 4)))
LEFT JOIN REC_MOVPER M ON T.REC_PERIODO = M.REC_PERIODO AND T.CON_RUT = M.CON_RUT
                         AND T.CON_CORREL = M.CON_CORREL AND T.RPR_PROCESO = M.RPR_PROCESO
                         AND T.TRA_RUT = M.TRA_RUT AND T.SUC_CODIGO = M.SUC_CODIGO AND T.USU_CODIGO = M.USU_CODIGO
-- JOIN condicional a CAJAS
LEFT JOIN REC_SUCURSAL S ON (TO_CHAR(p_con_correl) BETWEEN 600 AND 699) AND E.CON_CORREL = S.CON_CORREL AND E.CON_RUT = S.CON_RUT AND E.NRO_COMPROBANTE = S.NRO_COMPROBANTE AND E.REC_PERIODO = S.REC_PERIODO AND E.RPR_PROCESO = S.RPR_PROCESO
JOIN VIS_REC_CAJAS C ON
  ((TO_CHAR(p_con_correl) BETWEEN 600 AND 699 AND S.SUC_CCAF_ADH = C.ENT_CODIFICACION)
   OR (TO_CHAR(p_con_correl) NOT BETWEEN 600 AND 699 AND P.ENT_RUT = C.ENT_RUT))
WHERE TO_CHAR(E.REC_PERIODO, 'YYYY') = p_anio
  AND TO_CHAR(E.REC_PERIODO, 'MM') = p_mes
  AND E.CON_RUT = p_con_rut
  AND E.CON_CORREL = p_con_correl
  AND E.NRO_COMPROBANTE = p_nro_comprobante
  AND E.RPR_PROCESO = p_rpr_proceso
  AND (
    (TO_CHAR(p_tipo_corte) = 3 AND TO_CHAR(P.SUC_CODIGO) = TO_CHAR(p_cod_corte))
    OR (TO_CHAR(p_tipo_corte) = 4 AND TO_CHAR(P.USU_CODIGO) = TO_CHAR(p_cod_corte))
    OR (TO_CHAR(p_tipo_corte) NOT IN (3, 4))
  )
ORDER BY
  CASE 
    WHEN TO_CHAR(p_tipo_corte) = 1 THEN TO_CHAR(T.SUC_CODIGO)
    WHEN TO_CHAR(p_tipo_corte) = 2 THEN TO_CHAR(T.USU_CODIGO)
    ELSE TO_CHAR(T.TRA_RUT)
  END,
  T.TRA_RUT,
  T.TRA_APETRA,
  T.TRA_NOMTRA,
  T.SUC_CODIGO,
  T.USU_CODIGO,
  M.RTM_TIPO,
  M.MOV_FECINI,
  M.MOV_FECTER DESC;

    RETURN v_cursor;
END FNC_DET_CCAF;
/