----------------------VISTA AFPS-------------
CREATE OR REPLACE VIEW VIS_REC_AFPS AS
SELECT
    ENT_CODIFICACION,
    ENT_RUT,
    ENT_DIGITO,
    ENT_NOMBRE,
    ENT_TIPO
FROM
    REC_ENTPREV
WHERE
    ENT_TIPO = 1
    AND ENT_CODIFICACION <> 0
    AND ENT_ENTIDAD_APV = 1;

----------------------VISTA INP-------------
CREATE OR REPLACE VIEW VIS_REC_INP AS
		SELECT
		    ENT_CODIFICACION,
    ENT_RUT,
    ENT_DIGITO,
    ENT_NOMBRE,
    ENT_TIPO
		FROM
		    REC_ENTPREV
		WHERE
		    ENT_TIPO = 4;

----------------------VISTA INISAPRES-------------
 CREATE OR REPLACE VIEW VIS_REC_ISAPRES AS
		SELECT
		    ENT_CODIFICACION,
		    ENT_RUT,
		    ENT_DIGITO,
		    ENT_NOMBRE,
		    ENT_TIPO
		FROM
		    REC_ENTPREV
		WHERE
		    ENT_TIPO = 2;
    
 ----------------------VISTA CAJAS-------------
  CREATE OR REPLACE VIEW VIS_REC_CAJAS AS
SELECT
     ENT_CODIFICACION,
		    ENT_RUT,
		    ENT_DIGITO,
		    ENT_NOMBRE,
		    ENT_TIPO
FROM
    REC_ENTPREV
WHERE
    ENT_TIPO = 5
    AND ENT_CODIFICACION <> 0;